//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aria2Launcher.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aria2Launcher.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Comment 的本地化字符串。
        /// </summary>
        public static string Aria2Conf_Column_Comment {
            get {
                return ResourceManager.GetString("Aria2Conf_Column_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Aria2Conf_Column_Name {
            get {
                return ResourceManager.GetString("Aria2Conf_Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string Aria2Conf_Column_Value {
            get {
                return ResourceManager.GetString("Aria2Conf_Column_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aria2 Configure 的本地化字符串。
        /// </summary>
        public static string Aria2Configure {
            get {
                return ResourceManager.GetString("Aria2Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aria2 Dir: 的本地化字符串。
        /// </summary>
        public static string Aria2Dir {
            get {
                return ResourceManager.GetString("Aria2Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto start when system login 的本地化字符串。
        /// </summary>
        public static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BT Tracker source:  的本地化字符串。
        /// </summary>
        public static string BtTrackerSource {
            get {
                return ResourceManager.GetString("BtTrackerSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you need to build a default conf file 的本地化字符串。
        /// </summary>
        public static string Err_BuildConf {
            get {
                return ResourceManager.GetString("Err_BuildConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you need to download Aria2? 的本地化字符串。
        /// </summary>
        public static string Err_DownloadAria2 {
            get {
                return ResourceManager.GetString("Err_DownloadAria2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download failed, error code: 的本地化字符串。
        /// </summary>
        public static string Err_GetTracker {
            get {
                return ResourceManager.GetString("Err_GetTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find aria2.conf 的本地化字符串。
        /// </summary>
        public static string Err_NoAria2Conf {
            get {
                return ResourceManager.GetString("Err_NoAria2Conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find aria2c.exe 的本地化字符串。
        /// </summary>
        public static string Err_NoAria2Exe {
            get {
                return ResourceManager.GetString("Err_NoAria2Exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aria2 Exited 的本地化字符串。
        /// </summary>
        public static string Log_Aria2Exited {
            get {
                return ResourceManager.GetString("Log_Aria2Exited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Aria2 with RPC mode 的本地化字符串。
        /// </summary>
        public static string Log_Aria2RpcMode {
            get {
                return ResourceManager.GetString("Log_Aria2RpcMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 find aria2.conf 的本地化字符串。
        /// </summary>
        public static string Log_FindAria2Conf {
            get {
                return ResourceManager.GetString("Log_FindAria2Conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 find aria2c.exe 的本地化字符串。
        /// </summary>
        public static string Log_FindAria2Exe {
            get {
                return ResourceManager.GetString("Log_FindAria2Exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tracker list is successful Updated 的本地化字符串。
        /// </summary>
        public static string Log_TrackerUpdated {
            get {
                return ResourceManager.GetString("Log_TrackerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Window 的本地化字符串。
        /// </summary>
        public static string ShowWindow {
            get {
                return ResourceManager.GetString("ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Aria2 的本地化字符串。
        /// </summary>
        public static string StartAria2 {
            get {
                return ResourceManager.GetString("StartAria2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Aria2 的本地化字符串。
        /// </summary>
        public static string StopAria2 {
            get {
                return ResourceManager.GetString("StopAria2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update now 的本地化字符串。
        /// </summary>
        public static string UpdateTracker {
            get {
                return ResourceManager.GetString("UpdateTracker", resourceCulture);
            }
        }
    }
}
